# Neden NumPy?

In [16]:
a = [1,2,3,4]
b = [2,3,4,5]
a

[1, 2, 3, 4]

In [18]:
b

[2, 3, 4, 5]

In [23]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [25]:
import numpy as np

In [27]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [29]:
a * b

array([ 2,  6, 12, 20])

# Bir Liste Üzerinden NumPy Array'i Oluşturmak

In [191]:
import numpy as np

In [193]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [195]:
x = np.array([1,2,3,4,5])

In [197]:
type(x)

numpy.ndarray

In [199]:
np.array([3.14, 4, 2, 13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [201]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

# Sıfırdan Array Oluşturmak

In [51]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
np.ones((3,5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [59]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [63]:
np.arange(0,33,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [65]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [76]:
np.random.normal(10,3,(3,4))

array([[ 6.05591195,  6.74120987, 11.33030685, 12.80816129],
       [12.72895789, 11.86671553,  6.26313111,  9.0754243 ],
       [11.24119554,  9.7765757 , 10.60304889, 14.12833546]])

In [78]:
np.random.randint(0,10, (3,3))

array([[7, 7, 3],
       [3, 6, 2],
       [9, 4, 0]])

# NumPy Array Özellikleri

* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [4]:
import numpy as np

In [6]:
np.random.randint(10, size = 10)

array([0, 9, 1, 8, 3, 3, 0, 6, 2, 8])

In [8]:
k = np.random.randint(10, size = 10)
k

array([1, 2, 6, 7, 0, 0, 1, 8, 6, 4])

In [229]:
k.ndim

1

In [231]:
k.shape

(10,)

In [233]:
k.size

10

In [235]:
k.dtype

dtype('int32')

In [237]:
l = np.random.randint(10, size = (3,5))

In [239]:
l

array([[9, 5, 1, 3, 8],
       [9, 2, 9, 1, 4],
       [2, 7, 4, 0, 4]])

In [241]:
l.ndim

2

In [243]:
l.shape

(3, 5)

In [245]:
l.size

15

In [247]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme (Reshaping)

In [30]:
import numpy as np

In [32]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
c = np.arange(1,10)

In [37]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
c.ndim

1

In [41]:
d = c.reshape((1,9))

In [43]:
d

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [44]:
d.ndim

2

# Birleştirme (Concantenation)

In [49]:
import numpy as np

In [50]:
p = np.array([1,2,3])

In [52]:
r = np.array([4,5,6])

In [54]:
np.concatenate([p,r])

array([1, 2, 3, 4, 5, 6])

In [56]:
s = np.array([7,8,9])

In [59]:
np.concatenate([p,r,s])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2 Boyut üzerinden yapmak için:

In [62]:
h = np.array([[1,2,3],
              [4,5,6]])

In [63]:
np.concatenate([h,h])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# Sütun bazında birleştirmek için

In [66]:
np.concatenate([h,h], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [305]:
import numpy as np

In [309]:
g = np.array([1,2,3,99,99,3,2,1])

In [311]:
np.split(g, [3,5]) # 3,5 ayırmak için index no belirtiyor

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [313]:
a, b, c = np.split(g, [3,5]) # ayırma işleminden sonra atama yapıyoruz

In [315]:
a

array([1, 2, 3])

In [317]:
b

array([99, 99])

In [319]:
c

array([3, 2, 1])

# İki Boyutlu Ayırma

In [322]:
v = np.arange(16).reshape(4,4)
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [324]:
np.vsplit(v, [2]) # dikey şekilde 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [326]:
ust, alt = np.vsplit(v, [2])

In [328]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [330]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [336]:
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [344]:
np.hsplit(v, [2]) # yatay şekilde

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [346]:
sag, sol = np.hsplit(v, [2])

In [348]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [350]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Sıralama (Sorting)

In [355]:
import numpy as np

In [357]:
t = np.array([2,1,4,3,5])

In [359]:
t

array([2, 1, 4, 3, 5])

In [361]:
np.sort(t) # orijinal yapı bozulmaz

array([1, 2, 3, 4, 5])

In [363]:
t

array([2, 1, 4, 3, 5])

In [365]:
t.sort() # yapıyı bozar

In [367]:
t

array([1, 2, 3, 4, 5])

# İki Boyutlu Array Sıralama

In [370]:
n = np.random.normal(20,5, (3,3))

In [372]:
n

array([[ 8.01147434, 23.2952023 , 23.27891357],
       [31.65353117, 17.54647467, 16.14461731],
       [19.39748397, 14.35098927, 17.0639903 ]])

In [374]:
np.sort(n, axis = 1) # satırları sıralamak

array([[ 8.01147434, 23.27891357, 23.2952023 ],
       [16.14461731, 17.54647467, 31.65353117],
       [14.35098927, 17.0639903 , 19.39748397]])

In [376]:
np.sort(n, axis = 0) # sütunları sıralamak

array([[ 8.01147434, 14.35098927, 16.14461731],
       [19.39748397, 17.54647467, 17.0639903 ],
       [31.65353117, 23.2952023 , 23.27891357]])