# Index ile Elemanlara Erişmek

In [3]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([0, 3, 5, 6, 5, 0, 2, 5, 4, 2])

In [5]:
a[0]

0

In [7]:
a[-1]

2

In [9]:
a[0] = 100

In [11]:
a

array([100,   3,   5,   6,   5,   0,   2,   5,   4,   2])

# 2 Boyutlu Array'de Index ile Elemana Erişme

In [14]:
b = np.random.randint(10, size = (3,5))
b

array([[8, 6, 3, 9, 2],
       [2, 8, 9, 6, 3],
       [5, 5, 0, 5, 0]])

In [16]:
b[0,0]

8

In [22]:
b[1,2] # 1. satır, 2. sütun

9

In [24]:
b[1,2] = 99

In [28]:
b

array([[ 8,  6,  3,  9,  2],
       [ 2,  8, 99,  6,  3],
       [ 5,  5,  0,  5,  0]])

In [30]:
b [1,4] = 2.2

In [32]:
b

array([[ 8,  6,  3,  9,  2],
       [ 2,  8, 99,  6,  2],
       [ 5,  5,  0,  5,  0]])

In [34]:
# 2.2 olarak değil, 2 olarak girdi. farklı tip giremez.

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [52]:
import numpy as np

In [54]:
c = np.arange(20,30)
c

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [56]:
c[0:3]

array([20, 21, 22])

In [58]:
c[:3]

array([20, 21, 22])

In [60]:
c[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [62]:
c[1::2]

array([21, 23, 25, 27, 29])

# 2 Boyutlu Slice İşlemleri

In [65]:
d = np.random.randint(10, size = (5,5))

In [67]:
d

array([[2, 4, 3, 2, 6],
       [0, 4, 2, 4, 8],
       [9, 1, 8, 1, 2],
       [5, 5, 8, 6, 9],
       [6, 7, 8, 2, 4]])

In [69]:
d[:,0] # 0. sütunun tüm elemanlarına eriştik

array([2, 0, 9, 5, 6])

In [71]:
d[:,1] # 1. sütunun tüm elemanlarına eriştik

array([4, 4, 1, 5, 7])

In [73]:
d[:,4]

array([6, 8, 2, 9, 4])

In [75]:
d[0, :] # 0. satırın tüm elemanlarına eriştik

array([2, 4, 3, 2, 6])

In [79]:
d[0] # 0. satırın tüm elemanlarına eriştik

array([2, 4, 3, 2, 6])

In [83]:
d[1, :] # 1. satırın tüm elemanlarına eriştik

array([0, 4, 2, 4, 8])

In [85]:
d[0:2, 0:3] # 0'dan 2'ye kadar satırlar, 0'dan 3'e kadar sütunları al

array([[2, 4, 3],
       [0, 4, 2]])

In [89]:
d[::, 0:2]

array([[2, 4],
       [0, 4],
       [9, 1],
       [5, 5],
       [6, 7]])

In [93]:
d

array([[2, 4, 3, 2, 6],
       [0, 4, 2, 4, 8],
       [9, 1, 8, 1, 2],
       [5, 5, 8, 6, 9],
       [6, 7, 8, 2, 4]])

In [95]:
d[1:3, 0:2]

array([[0, 4],
       [9, 1]])

# Alt Küme Üzerinde İşlem Yapmak

In [100]:
import numpy as np
e = np.random.randint(10, size = (5,5))
e

array([[4, 4, 9, 5, 4],
       [8, 3, 9, 4, 3],
       [8, 0, 2, 0, 8],
       [4, 6, 6, 7, 6],
       [8, 4, 3, 0, 5]])

In [102]:
altKume = e[0:3, 0:2]
altKume

array([[4, 4],
       [8, 3],
       [8, 0]])

In [104]:
altKume[0,0] = 99999
altKume[1,1] = 888

In [108]:
altKume

array([[99999,     4],
       [    8,   888],
       [    8,     0]])

In [110]:
e

array([[99999,     4,     9,     5,     4],
       [    8,   888,     9,     4,     3],
       [    8,     0,     2,     0,     8],
       [    4,     6,     6,     7,     6],
       [    8,     4,     3,     0,     5]])

In [2]:
# Asıl array bozuldu ^^

In [114]:
f = np.random.randint(10, size = (5,5))
f

array([[7, 5, 0, 4, 2],
       [1, 6, 5, 3, 7],
       [5, 5, 2, 9, 0],
       [1, 0, 1, 1, 1],
       [7, 5, 3, 8, 9]])

In [118]:
altKume2 = f[0:3, 0:2].copy()
altKume2

array([[7, 5],
       [1, 6],
       [5, 5]])

In [120]:
altKume2[0,0] = 571

In [122]:
altKume2

array([[571,   5],
       [  1,   6],
       [  5,   5]])

In [124]:
f

array([[7, 5, 0, 4, 2],
       [1, 6, 5, 3, 7],
       [5, 5, 2, 9, 0],
       [1, 0, 1, 1, 1],
       [7, 5, 3, 8, 9]])

In [4]:
# İlk array'de değişiklik olmadı ^^

# Fancy Index ile Elemanlara Erişmek

In [129]:
import numpy as np
x = np.arange(0, 30, 3)
x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [131]:
x[1]

3

In [133]:
x[3]

9

In [135]:
x[5]

15

In [137]:
x[1], x[3], x[5]

(3, 9, 15)

In [139]:
getir = [1,3,5] # fancy indexing ile belirli dizinlerdeki elemanlara erişmek için kullanılır.

In [141]:
x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [145]:
x[getir] #  NumPy dizisi x'in 1., 3., ve 5. indekslerindeki elemanları seçer.

array([ 3,  9, 15])

# 2 Boyutta Fancy

In [148]:
y = np.arange(9).reshape((3,3))

In [150]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [154]:
satır = np.array([0,1])
sütun = np.array([1,2])

In [156]:
y[satır, sütun]

array([1, 5])

In [158]:
# basit index ile fancy index

In [160]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [162]:
y[0, [1,2]]

array([1, 2])

In [164]:
#slice ile fancy

In [168]:
y[0: , [1,2]] # hem slice hem de fancy işlemi var

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [173]:
import numpy as np
z = np.array([1,2,3,4,5])

In [175]:
z > 5 # her eleman için sorgular

array([False, False, False, False, False])

In [177]:
z < 3

array([ True,  True, False, False, False])

In [179]:
z[z < 3] # True olanlar gelecek

array([1, 2])

In [183]:
z[z >= 5]

array([5])

In [185]:
z[z == 2]

array([2])

In [187]:
z[z != 2]

array([1, 3, 4, 5])

In [189]:
z * 2

array([ 2,  4,  6,  8, 10])

In [191]:
z / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [193]:
z*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [195]:
z ** 2

array([ 1,  4,  9, 16, 25])