# Matematiksel İşlemler

In [6]:
import numpy as np
a = np.array([1,2,3,4,5])

In [8]:
a - 1 # tüm elemanlara işlem uygulanır

array([0, 1, 2, 3, 4])

In [35]:
a * 5

array([ 5, 10, 15, 20, 25])

In [37]:
a ** 2

array([ 1,  4,  9, 16, 25])

In [41]:
a % 2

array([1, 0, 1, 0, 1], dtype=int32)

# ufunc

In [19]:
np.subtract(a, 1) # a - 1

array([0, 1, 2, 3, 4])

In [25]:
np.add(a, 1) # a + 1

array([2, 3, 4, 5, 6])

In [27]:
np.multiply(a , 4) # a * 4

array([ 4,  8, 12, 16, 20])

In [31]:
np.divide(a, 3) # a / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [39]:
np.power(a, 3) # a ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [45]:
np.mod(a,2) # a % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [47]:
np.absolute(np.array([-3])) # mutlak değer için

array([3])

In [49]:
np.sin(360)

0.9589157234143065

In [51]:
np.cos(180)

-0.5984600690578581

In [53]:
b = np.array([1,2,3])

In [55]:
np.log(b)

array([0.        , 0.69314718, 1.09861229])

In [59]:
np.log2(b)

array([0.       , 1.       , 1.5849625])

In [57]:
np.log10(b)

array([0.        , 0.30103   , 0.47712125])

# İstatiksel Hesaplamalar

In [64]:
b

array([1, 2, 3])

In [66]:
np.mean(b)

2.0

In [84]:
b.sum()

6

In [76]:
b.min()

1

In [78]:
b.max()

3

In [82]:
np.var(b)

0.6666666666666666

In [88]:
np.std(b)

0.816496580927726

In [98]:
np.corrcoef(b)

1.0

# Numpy ile İki Bilinmeyenli Denklem Çözümü

In [103]:
import numpy as np

5 * x0 + x1 = 12
x0 + 3 * x1 = 10

In [108]:
c = np.array([[5,1], [1,3]]) # katsayıları
d = np.array([12,10])

In [110]:
c

array([[5, 1],
       [1, 3]])

In [112]:
d

array([12, 10])

In [116]:
x = np.linalg.solve(c, d)
x

array([1.85714286, 2.71428571])