In [7]:
import numpy as np

## Soru 1

Aşağıda "m" ismindeki bir array'in çıktısı verilmiştir. Buna göre yazılan kodun çıktısı nedir?

Çıktı:

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Kod:

m[0, [1,2]]

### Çözüm

In [12]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
m[0, [1,2]]

array([1, 2])

In [16]:
# Kodda m[0, [1,2]] ifadesi, m array'inin 0. satırında, 1. ve 2. sütunlardaki değerleri seçmek anlamına gelir.

----------------------------------------------------------------------------------------------------------------

# Soru 2

Aşağıda "a" ismindeki bir array'in çıktısı verilmiştir. Buna göre yazılan kodun çıktısı nedir?

Çıktı:

array([[4, 7, 4, 5, 9],
            [2, 5, 0, 7, 7],
            [1, 9, 0, 8, 2]])

Kod:

a[:2, :3]

In [ ]:
# -- Kodda a[:2, :3] ifadesi, a array'inin ilk iki satırını (0 ve 1. satırlar) 
# -- ve ilk üç sütununu (0, 1 ve 2. sütunlar) seçmek anlamına gelir.

Buna göre, a[:2, :3] kodunun çıktısı:

array([[4, 7, 4],
       [2, 5, 0]])


----------------------------------------------------------------------------------------------------------------

In [22]:
np.array([3.14, 4,6,1.2]) # çıktısı nedir?

array([3.14, 4.  , 6.  , 1.2 ])

----------------------------------------------------------------------------------------------------------------

# Soru 3

Aşağıda “a” ismindeki bir array’in çıktısı verilmiştir. Buna göre yazılan kodun çıktısı hangisidir?

 

Çıktı:

array([[4, 7, 4, 5, 9],

       [2, 5, 0, 7, 7],

       [1, 9, 0, 8, 2]])



Kod:

a[2,3]

## Çözüm

8

----------------------------------------------------------------------------------------------------------------

# Soru 4

Aşağıdaki çıktıyı üretmek için hangi kod yazılmalıdır?
 

array([[1., 1., 1.],

       [1., 1., 1.]])

## Çözüm

In [42]:
array = np.ones((2, 3)) 
# 2x3 boyutunda ve tüm elemanları 1.0 olan bir array oluşturma
array

array([[1., 1., 1.],
       [1., 1., 1.]])

----------------------------------------------------------------------------------------------------------------

# Soru 5

Bir numpy array’nin alt kümesi üzerinde işlem yaparken alt küme üzerinde yapılan değişikliklerin array’in ilk halinden bağımsız olması için hangi fonksiyon kullanılır?

## Çözüm

copy()

----------------------------------------------------------------------------------------------------------------

# Soru 6

Aşağıda "v" ismindeki bir array'in çıktısı verilmiştir. Buna göre yazılan kodun çıktısı nedir?

Çıktı:

array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])

Kod:

[v[1], v[3]]

## Çözüm

In [60]:
b = np.arange(0,30,3)

In [62]:
b

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [64]:
[b[1], b[3]]

[3, 9]

----------------------------------------------------------------------------------------------------------------

# Soru 7

Aşağıda "v" ismindeki bir array'in çıktısı verilmiştir. Buna göre yazılan kodun çıktısı nedir?

Çıktı:

array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])

Kod:

[v[9], v[0]]

## Çözüm

In [80]:
c = np.arange(0,30,3)
c

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [82]:
[c[9], c[0]]

[27, 0]

----------------------------------------------------------------------------------------------------------------

# Soru 8

Aşağıda verilen çıktının kodu hangisidir?

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Çözüm

In [95]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

----------------------------------------------------------------------------------------------------------------

# Soru 9

Aşağıda “a” ismindeki bir array’in çıktısı verilmiştir. Buna göre yazılan kodun çıktısı hangisidir?

 

Çıktı:

array([[4, 0, 3, 0, 1],

            [9, 6, 1, 5, 9],

            [1, 9, 0, 8, 2]])



Kod:

a[0:1]

## Çözüm

In [106]:
# --- Kodda a[0:1] ifadesi kullanılmıştır. Bu ifade, array'in ilk satırını seçer. 
# --- Ancak dikkat edilmesi gereken nokta, slicing işlemi sonucu elde edilen alt kümenin bir dizi (array) şeklinde döneceğidir.

# --- a[0:1] ifadesi, 0. indekste bulunan satırı seçer (yani ilk satırı), 
# --- ancak sonuçta bu, bir dizi olarak dönecektir.

In [108]:
# --- Sonuç olarak, kodun çıktısı şu şekilde olacaktır:
# ---array([[4, 0, 3, 0, 1]])
